export const LOGIN = 'LOGIN'
export const SOCIAL = 'SOCIAL'
export const REGISTER = 'REGISTER'
export const EMAIL_VERIFICATION = 'EMAIL_VERIFICATION'
export const RESETPASSWORD = 'RESETPASSWORD'
export const SEND_EMAIL_FORGET = 'SEND_EMAIL_FORGET'
export const RESEND_CODE = 'RESEND_CODE'
export const SENDOTPBYEMAIL = 'SENDOTPBYEMAIL'
export const SET_USER_INFO = 'SET_USER_INFO'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_USER_PURCHASE = 'FETCH_USER_PURCHASE'

export const FETCH_HOME = 'FETCH_HOME'
export const FETCH_CONSTRAINS = 'FETCH_CONSTRAINS'
export const FETCH_FITERS = 'FETCH_FITERS'
export const FETCH_ADVERTISING = 'FETCH_ADVERTISING'
export const FETCH_DEAL_DETAILS = 'FETCH_DEAL_DETAILS'
export const FETCH_REVIEWS = 'FETCH_REVIEWS'
export const CART_CHANGES = 'CART_CHANGES'
export const HOME_MAHALATY = 'HOME_MAHALATY'
export const PROFILE_CHANGES = 'PROFILE_CHANGES'
export const SELECTED_LOCATION = 'SELECTED_LOCATION'
export const NAVIGATE = 'NAVIGATE'
export const LEAVE_COMMENTS = 'LEAVE_COMMENTS'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPLOAD_PROFILE = 'UPLOAD_PROFILE'
export const CITIES = 'CITIES'
export const AREAS = 'AREAS'
export const ORDERS = 'ORDERS'
export const CONFIRM_ORDER = 'CONFIRM_ORDER'
export const ORDERS_DETAILS = 'ORDERS_DETAILS'
export const SELECT_MEAL = 'SELECT_MEAL'
export const REFREASH_ORDERS = 'REFREASH_ORDERS'
export const REFREASH_APP = 'REFREASH_APP'
export const REFREASH_APP_LOCATION = 'REFREASH_APP_LOCATION'
export const REFREASH_ADDRESS = 'REFREASH_ADDRESS'
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const NOTIFICATIONS_SUCSSESS = 'NOTIFICATIONS_SUCSSESS'



export const CONFIRM_ORDER_GUEST = 'CONFIRM_ORDER_GUEST'


export const CONTACTUS = 'CONTACTUS'
export const LEAVE_REVIEW = 'LEAVE_REVIEW'
export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS'
export const CATEGORIES = 'CATEGORIES'
export const TYPES = 'TYPES'
export const FARMER_DETAILS = 'FARMER_DETAILS'
export const KITCHENS = 'KITCHENS'
export const KITCHENSALL = 'KITCHENSALL'
export const MEALSBYKITCHEN = 'MEALSBYKITCHEN'
export const KITCHENSALLNBYLOCATION = 'KITCHENSALLNBYLOCATION'
export const FEATURED_MEALS = 'FEATURED_MEALS'
export const FAVOURITE_PRODUCTS = 'FAVOURITE_PRODUCTS'
export const GET_FAVOURITE_PRODUCTS = 'GET_FAVOURITE_PRODUCTS'


export const GET_USER_ADDRESSES = 'GET_USER_ADDRESSES'
export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS'
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS'
export const DELETE_USER_ADDRESS = 'DELETE_USER_ADDRESS'


export const GET_FARMERS = 'GET_FARMERS'
export const SELECT_CONSTRAINS = 'SELECT_CONSTRAINS'



export const OFFERS = 'OFFERS'
export const SUBSCRIPION = 'SUBSCRIPION'
export const SELECTED_ADDRESS = 'SELECTED_ADDRESS'
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY'



export const CATEGORIES_MAIN = 'CATEGORIES_MAIN'
export const CATEGORIES_SUB = 'CATEGORIES_SUB'
export const SHOPS = 'SHOPS'
export const SHOP_CATEGORIES = 'SHOP_CATEGORIES'
export const SHOP = 'SHOP'
export const SELECTED_SHOP = 'SELECTED_SHOP'
export const MAIN_CATEGORY_DETAILS = 'MAIN_CATEGORY_DETAILS'



export const PRODUCT = 'PRODUCT'
export const FCM = 'FCM'
export const GUEST_CHECKOUT = 'GUEST_CHECKOUT'
export const FETCH_ABOUT = 'FETCH_ABOUT'
export const UPDATE_ORDER = 'UPDATE_ORDER'



export const REFREASH_NOTIIFCATIONS = 'REFREASH_NOTIIFCATIONS'
export const REFREASH_HOME = 'REFREASH_HOME'

