export default {
  login: {
    userInfo: {},
    selectedLocation: {
      location: "Your location could not be determined",
      geometry: { lat: 25.2048493, lng: 55.2707828 },
    },
  },
  isConnected: false,
  cart: {
    cart: {},
    list: [],
    selectedProduct: {},
    constrains: {},
  },
  constrains: {},
  banners: [],
  RefrashApp: 0,
  RefrashAppLocation: 0,
  featuredMeals: [],
  meals: [],
  kitchens: [],
  selectedAddress: {},
  selectedCategory: {},
  selectedShop: {},
  categories: [],
  mainCategories: [],
  subCategories: [],
  fcm: "",
  GuestCheckoutAddress: {},
  RefrashNotifications: 0,
  RefrashHome: 0,
  totalCount: 0,
};
